name: Publish
on:
  push:
    tags:
      - v*
permissions:
  id-token: write
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: npm
    name: Publish
    steps:
      - uses: holepunchto/actions/node-base@v1
      - uses: holepunchto/actions/compile-prebuilds@v1
        with:
          platform: linux
          arch: x64
          prefix: .
      - uses: holepunchto/actions/publish@v1
